"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Badge } from "@/components/ui/badge";
import Header from "@/components/custom/header";
import { Sidebar } from "@/components/custom/side-bar/sidebar";
import { cn } from "@/lib/utils"; // Make sure to import the cn utility
import { isKeyObject } from "util/types";
import { useState } from "react";
import { SidebarToggle } from "@/components//custom/side-bar/sidebar-toggle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true); // Add state for sidebar

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="container mx-auto flex min-h-screen flex-col gap-4 px-2 py-4 md:px-4 md:py-8">
          <div className="relative flex flex-1 flex-col rounded-lg border border-border/50 bg-background/50 p-4 backdrop-blur-[2px] sm:p-8">
            {children}
            <Badge
              variant="outline"
              className="absolute -top-2.5 left-4 bg-background sm:left-8"
            >
              Work in progress
            </Badge>
          </div>
        </main>
        <div className="flex min-h-screen flex-col">
          <Sidebar isOpen={isSidebarOpen} setIsOpen={setIsSidebarOpen} />

          <main
            className={cn(
              "container mx-auto flex min-h-screen flex-col gap-4 px-2 py-4 md:px-4 md:py-8",
              isSidebarOpen ? "lg:ml-72" : "lg:ml-[0px]"
            )}
          >
            <SidebarToggle isOpen={isSidebarOpen} setIsOpen={setIsSidebarOpen} />
            <div className="relative flex flex-1 flex-col rounded-lg border border-border/50 bg-background/50 p-4 backdrop-blur-[2px] sm:p-8">
              {children}
              <Badge
                variant="outline"
                className="absolute -top-2.5 left-4 bg-background sm:left-8"
              >
                Work in progress
              </Badge>
            </div>
          </main>
          <footer
            className={cn(
              "transition-[margin-left] ease-in-out duration-300",
              isSidebarOpen ? "lg:ml-72" : "lg:ml-[90px]"
            )}
          >
            {/* Add your footer content here */}
          </footer>
        </div>
      </body>
    </html>
  );
}
